language: python

python:
   - "2.7"
   - "3.6"

matrix:
 allow_failures:
   - python: "3.6"

install:
   - python setup.py install
   - pip install -r dev-requirements.txt

script:
  - py.test -vv --cov=[REPOSITORY_NAME] --cov-report xml tests

after_script:
  - python-codacy-coverage -r coverage.xml