sudo: false
language: python

python: "3.6"

cache:
  - pip
  - apt

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

before_install:
  - pip install -r thog_secret_requirements.txt
  - wget https://raw.githubusercontent.com/lookcrabs/TruffleHog_Scripts/master/th_wrapper.py
  - python th_wrapper.py -w truffles.json -c thog_config.json -g file:///${PWD}/ --check

# run tests
script:
  - py.test -vv --cov=SERVICE_NAME --cov-report xml tests

after_script:
  - python-codacy-coverage -r coverage.xml
