definitions: {}
info:
  contact:
    email: cdis@uchicago.edu
  description: A service template for CDIS Gen 3 data commons. Code is available on
    [GitHub](https://github.com/uc-cdis/template-repo).
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://cdis.uchicago.edu/terms/
  title: Service template OpenAPI Specification
  version: '1.0'
paths:
  /_status:
    get:
      responses:
        '200':
          description: Healthy
        default:
          description: Unhealthy
      summary: Health check endpoint
      tags:
      - system
  /admin:
    get:
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      summary: Admin endpoint
      tags:
      - admin
  /admin/is_admin:
    get:
      responses:
        '200':
          description: User is admin
        '403':
          description: User is not admin
      summary: Admin endpoint
      tags:
      - admin
  /something:
    get:
      responses:
        '200':
          description: Success
      summary: Get something
    put:
      responses:
        '200':
          description: Success
      summary: Put something
  /something/bar:
    get:
      responses:
        '200':
          description: Success
      summary: bar!
  /something/foo/{param}:
    get:
      parameters:
      - in: path
        name: param
        required: true
        type: string
      responses:
        '200':
          description: Success
      summary: foo!
  /something/put-get:
    get:
      description: <br/>GET and PUT have the same documentation:<br/>
      responses:
        '200':
          description: Success
      summary: Several methods for the same function
    put:
      description: <br/>GET and PUT have the same documentation:<br/>
      responses:
        '200':
          description: Success
      summary: Several methods for the same function
  /user_endpoint:
    get:
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
      summary: User endpoint
swagger: '2.0'
